package br.com.sptech.projeto.encapsulamento1;

public class TelaAluno extends javax.swing.JFrame {

//criar um aluno
    Aluno aluno1 = new Aluno("#123", "Giuliana", "ADS");

    public TelaAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloAluno1 = new javax.swing.JLabel();
        btnVerificarAluno1 = new javax.swing.JButton();
        lblResultadoAluno1 = new javax.swing.JLabel();
        txt01 = new javax.swing.JLabel();
        inputNota01 = new javax.swing.JTextField();
        txt02 = new javax.swing.JLabel();
        inputNota2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloAluno1.setText("Aluno 01");

        btnVerificarAluno1.setText("Verificar Aprovação");
        btnVerificarAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarAluno1ActionPerformed(evt);
            }
        });

        lblResultadoAluno1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblResultadoAluno1.setText("----");

        txt01.setText("Nota 1");

        inputNota01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNota01ActionPerformed(evt);
            }
        });

        txt02.setText("Nota 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt01)
                            .addComponent(txt02))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputNota2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(inputNota01)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultadoAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerificarAluno1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(lblTituloAluno1)))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblTituloAluno1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt01, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNota01, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt02))
                .addGap(46, 46, 46)
                .addComponent(btnVerificarAluno1)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoAluno1)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarAluno1ActionPerformed

        String nota1Digitada = inputNota01.getText();
        String nota2Digitada = inputNota01.getText();
        
        
        Double nota01 = Double.valueOf(nota1Digitada);
        Double nota02 = Double.valueOf(nota2Digitada);

        aluno1.setNota1(nota01);
        aluno1.setNota2(nota02);

    }//GEN-LAST:event_btnVerificarAluno1ActionPerformed

    private void inputNota01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNota01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNota01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificarAluno1;
    private javax.swing.JTextField inputNota01;
    private javax.swing.JTextField inputNota2;
    private javax.swing.JLabel lblResultadoAluno1;
    private javax.swing.JLabel lblTituloAluno1;
    private javax.swing.JLabel txt01;
    private javax.swing.JLabel txt02;
    // End of variables declaration//GEN-END:variables
}
